    Finished test [unoptimized] target(s) in 0.08s
     Running unittests src/lib.rs (/home/y00577373/analysis/target/debug/deps/ide-993b25a6535f9b56)

running 790 tests
test analysis_is_send ... ok
test doc_links::intra_doc_links::tests::test_name ... ok
test annotations::fn_references::tests::test_find_trait_methods ... ok
test annotations::fn_references::tests::test_find_all_methods ... ok
test annotations::fn_references::tests::test_skip_tests ... ok
test annotations::tests::test_no_annotations_outside_module_tree ... ok
test doc_links::tests::external_docs_doc_url_std_crate ... ok
test doc_links::tests::external_docs_module ... ok
test doc_links::tests::external_docs_doc_url_struct ... ok
test annotations::tests::test_no_annotations_macro_struct_def ... ok
test doc_links::tests::external_docs_trait ... ok
test doc_links::tests::external_docs_doc_url_crate ... ok
test doc_links::tests::external_docs_doc_url_struct_field ... ok
test doc_links::tests::doc_links_inherent_impl_items ... ok
test doc_links::tests::rewrite_on_field ... ok
test extend_selection::tests::test_extend_selection_doc_comments ... ok
test doc_links::tests::external_docs_doc_url_fn ... ok
test annotations::tests::runnable_annotation ... ok
test doc_links::tests::rewrite_html_root_url ... ok
test extend_selection::tests::test_extend_selection_prefer_idents ... ok
test folding_ranges::tests::fold_record_literals ... ok
test folding_ranges::tests::fold_region ... ok
test folding_ranges::tests::fold_consecutive_const ... ok
test folding_ranges::tests::fold_multiline_params ... ok
test folding_ranges::tests::fold_big_calls ... ok
test folding_ranges::tests::fold_multiline_array ... ok
test folding_ranges::tests::fold_return_type ... ok
test extend_selection::tests::test_extend_selection_start_of_the_line ... ok
test folding_ranges::tests::fold_where_clause ... ok
test folding_ranges::tests::test_fold_imports ... ok
test folding_ranges::tests::fold_consecutive_static ... ok
test doc_links::tests::doc_links_trait_impl_items ... ok
test folding_ranges::tests::test_fold_comments ... ok
test folding_ranges::tests::test_fold_match_arms ... ok
test extend_selection::tests::test_extend_selection_prefer_lifetimes ... ok
test folding_ranges::tests::test_fold_import_groups ... ok
test extend_selection::tests::test_extend_selection_on_tuple_in_type ... ok
test expand_macro::tests::macro_expand_as_keyword ... ok
test extend_selection::tests::test_extend_selection_arith ... ok
test folding_ranges::tests::test_folds_structs ... ok
test folding_ranges::tests::test_fold_import_and_groups ... ok
test folding_ranges::tests::test_folds_traits ... ok
test doc_links::tests::doc_links_trait_items ... ok
test folding_ranges::tests::test_folds_macros ... ok
test annotations::tests::test_annotations ... ok
test expand_macro::tests::macro_expand_multiple_lines ... ok
test extend_selection::tests::test_extend_selection_string ... ok
test extend_selection::tests::test_extend_selection_select_first_word ... ok
test extend_selection::tests::test_extend_selection_comments ... ok
test extend_selection::tests::test_extend_selection_on_tuple_in_rvalue ... ok
test folding_ranges::tests::test_fold_multiline_non_block_match_arm ... ok
test doc_links::tests::external_docs_doc_url_trait_assoc ... ok
test folding_ranges::tests::test_fold_mods ... ok
test expand_macro::tests::macro_expand_with_dyn_absolute_path ... ok
test extend_selection::tests::test_extend_selection_on_tuple_pat ... ok
test goto_declaration::tests::goto_decl_module_inline ... ok
test call_hierarchy::tests::test_call_hierarchy_in_macros_outgoing ... ok
test expand_macro::tests::macro_expand_recursive_expansion ... ok
test goto_declaration::tests::goto_decl_goto_def_fallback ... ok
test goto_definition::tests::goto_def_for_extern_crate ... ok
test goto_declaration::tests::goto_decl_module_outline ... ok
test doc_links::tests::external_docs_reexport_order ... ok
test expand_macro::tests::macro_expand_inner_macro_rules ... ok
test expand_macro::tests::macro_expand_inner_macro_fail_to_expand ... ok
test expand_macro::tests::macro_expand_underscore ... ok
test goto_definition::tests::goto_def_at_start_of_item ... ok
test doc_links::tests::doc_links_items_simple ... ok
test expand_macro::tests::macro_expand_with_dollar_crate ... ok
test goto_definition::tests::goto_def_for_intra_doc_link_same_file ... ok
test annotations::tests::test_annotations_appear_above_whole_item_when_configured_to_do_so ... ok
test call_hierarchy::tests::test_call_hierarchy_outgoing ... ok
test call_hierarchy::tests::test_call_hierarchy_outgoing_in_different_files ... ok
test goto_declaration::tests::goto_decl_constructor_shorthand ... ok
test goto_definition::tests::goto_def_for_intra_doc_link_inner ... ok
test call_hierarchy::tests::test_call_hierarchy_on_def ... ok
test file_structure::tests::test_file_structure ... ok
test extend_selection::tests::extend_selection_inside_macros ... ok
test goto_definition::tests::goto_def_for_macros_in_use_tree ... ok
test goto_definition::tests::goto_def_for_macro_container ... ok
test doc_links::tests::external_docs_doc_url_impl_assoc ... ok
test expand_macro::tests::macro_expand_match_ast_inside_let_statement ... ok
test goto_definition::tests::goto_def_for_enum_variant_self_expr_const ... ok
test goto_declaration::tests::goto_decl_field_pat_shorthand ... ok
test goto_definition::tests::goto_def_for_renamed_extern_crate ... ok
test goto_definition::tests::goto_def_for_type_alias_generic_parameter ... ok
test call_hierarchy::tests::test_call_hierarchy_on_ref ... ok
test goto_definition::tests::goto_def_for_module_declaration ... ok
test goto_definition::tests::goto_def_for_enum_variant_field ... ok
test extend_selection::tests::test_extend_trait_bounds_list_in_where_clause ... ok
test doc_links::tests::rewrite_struct ... ok
test extend_selection::tests::test_extend_trait_bounds_list_inline ... ok
test annotations::tests::struct_references_annotations ... ok
test goto_definition::tests::goto_def_for_field_init_shorthand ... ok
test call_hierarchy::tests::test_call_hierarchy_in_same_fn ... ok
test annotations::tests::const_annotations ... ok
test call_hierarchy::tests::test_call_hierarchy_in_different_files ... ok
test call_hierarchy::tests::test_call_hierarchy_incoming_outgoing ... ok
test goto_definition::tests::goto_def_for_enum_variant_self_pattern_const ... ok
test extend_selection::tests::extend_selection_inside_recur_macros ... ok
test goto_definition::tests::goto_def_for_use_alias ... ok
test goto_definition::tests::goto_def_for_macros ... ok
test goto_definition::tests::goto_def_for_macros_from_other_crates ... ok
test goto_definition::tests::goto_def_for_macro_defined_fn_with_arg ... ok
test call_hierarchy::tests::test_call_hierarchy_in_different_fn ... ok
test goto_definition::tests::goto_def_for_fields ... ok
test extend_selection::tests::test_extend_selection_list ... ok
test goto_definition::tests::goto_def_for_use_alias_foo_macro ... ok
test call_hierarchy::tests::test_call_hierarchy_in_tests_mod ... ok
test goto_definition::tests::goto_def_for_macro_defined_fn_no_arg ... ok
test goto_definition::tests::goto_def_of_trait_impl_type_alias ... ok
test goto_definition::tests::goto_def_for_record_pat_fields ... ok
test goto_definition::tests::goto_def_for_record_fields ... ok
test goto_definition::tests::goto_def_for_enum_variant_self_expr_record ... ok
test doc_links::tests::external_docs_doc_url_impl_trait_assoc ... ok
test goto_definition::tests::goto_def_of_trait_impl_const ... ok
test goto_definition::tests::goto_for_type_param ... ok
test expand_macro::tests::macro_expand_match_ast ... ok
test goto_definition::tests::goto_def_for_enum_variant_self_pattern_record ... ok
test goto_definition::tests::goto_def_if_items_same_name ... ok
test goto_definition::tests::goto_def_in_items ... ok
test goto_definition::tests::goto_def_for_methods ... ok
test goto_definition::tests::goto_doc_include_str ... ok
test goto_definition::tests::goto_def_for_assoc_ty_ufcs ... ok
test annotations::tests::struct_and_trait_impls_annotations ... ok
test goto_definition::tests::goto_impl_of_trait_fn::cursor_on_impl ... ok
test goto_definition::tests::goto_def_for_assoc_ty_in_path ... ok
test goto_definition::tests::goto_def_for_record_fields_macros ... ok
test goto_definition::tests::goto_def_for_ufcs_trait_methods_through_traits ... ok
test goto_definition::tests::goto_lifetime_param_decl ... ok
test goto_definition::tests::goto_self_param_on_decl ... ok
test goto_definition::tests::goto_def_in_local_fn ... ok
test call_hierarchy::tests::test_call_hierarchy_issue_5103 ... ok
test goto_definition::tests::goto_intra_doc_links ... ok
test annotations::tests::method_annotations ... ok
test goto_definition::tests::goto_label ... ok
test call_hierarchy::tests::test_trait_method_call_hierarchy ... ok
test goto_declaration::tests::goto_decl_assoc_item_no_impl_item ... ok
test goto_definition::tests::goto_def_in_local_macro ... ok
test goto_definition::tests::goto_lifetime_param_on_decl ... ok
test expand_macro::tests::macro_expand_derive ... ok
test goto_definition::tests::goto_definition_resolves_correct_name ... ok
test goto_definition::tests::goto_include ... ok
test goto_definition::tests::goto_lifetime_hrtb_for_type ... ok
test goto_definition::tests::goto_shadow_include ... ok
test goto_definition::tests::goto_incomplete_field ... ok
test goto_declaration::tests::goto_decl_assoc_item ... ok
test goto_definition::tests::goto_lifetime_hrtb ... ok
test goto_definition::tests::goto_for_tuple_fields ... ok
test goto_definition::tests::goto_definition_works_for_macro_inside_pattern ... ok
test goto_definition::tests::goto_lifetime_param_decl_nested ... ok
test goto_definition::tests::goto_definition_works_for_macro_inside_match_arm_lhs ... ok
test goto_definition::tests::goto_def_for_ufcs_inherent_methods ... ok
test goto_definition::tests::goto_proc_macro ... ok
test goto_implementation::tests::goto_implementation_for_trait ... ok
test goto_definition::tests::goto_def_for_assoc_ty_ufcs_multiple ... ok
test goto_implementation::tests::goto_implementation_for_trait_multiple_files ... ok
test call_hierarchy::tests::test_call_hierarchy_in_macros_incoming ... ok
test goto_implementation::tests::goto_implementation_adt_generic ... ok
test goto_implementation::tests::goto_implementation_trait_assoc_const ... ok
test goto_definition::tests::goto_self_param_ty_specified ... ok
test highlight_related::tests::test_hl_break_unlabeled_loop ... ok
test highlight_related::tests::test_hl_break_labeled_block ... ok
test goto_implementation::tests::goto_implementation_builtin ... ok
test highlight_related::tests::test_hl_break_unlabeled_block_in_loop ... ok
test goto_implementation::tests::goto_implementation_works ... ok
test highlight_related::tests::test_hl_break_loop ... ok
test highlight_related::tests::test_hl_break_for ... ok
test goto_implementation::tests::goto_implementation_type_alias ... ok
test highlight_related::tests::test_hl_break_and_continue ... ok
test highlight_related::tests::test_hl_break_loop2 ... ok
test highlight_related::tests::test_hl_break_for_but_not_continue ... ok
test highlight_related::tests::test_hl_disabled_ref_local ... ok
test goto_definition::tests::goto_definition_on_self_in_trait_impl ... ok
test highlight_related::tests::test_hl_break_while ... ok
test highlight_related::tests::test_hl_continue_for_but_not_break ... ok
test goto_definition::tests::goto_from_macro ... ok
test goto_type_definition::tests::goto_def_for_type_fallback ... ok
test goto_type_definition::tests::goto_def_for_struct_field ... ok
test goto_type_definition::tests::goto_def_for_enum_struct_field ... ok
test goto_implementation::tests::goto_implementation_all_impls ... ok
test goto_implementation::tests::goto_implementation_works_multiple_mods ... ok
test goto_type_definition::tests::goto_type_definition_for_param ... ok
test goto_definition::tests::goto_def_in_mac_call_in_attr_invoc ... ok
test goto_implementation::tests::goto_implementation_trait_functions ... ok
test goto_implementation::tests::goto_implementation_works_multiple_blocks ... ok
test highlight_related::tests::test_hl_disabled_ref_local_preserved_exit ... ok
test highlight_related::tests::test_hl_disabled_ref_local_preserved_yield ... ok
test highlight_related::tests::test_hl_disabled_ref_local_preserved_break ... ok
test goto_implementation::tests::goto_implementation_works_multiple_files ... ok
test goto_definition::tests::goto_ident_from_pat_macro ... ok
test highlight_related::tests::test_assoc_type_highlighting ... ok
test highlight_related::tests::test_hl_exit_points2 ... ok
test highlight_related::tests::test_hl_exit_points ... ok
test highlight_related::tests::test_hl_exit_points3 ... ok
test goto_definition::tests::goto_def_for_super_assoc_ty_in_path ... ok
test highlight_related::tests::test_hl_inner_tail_exit_points_labeled_block ... ok
test highlight_related::tests::test_hl_disabled_break ... ok
test goto_definition::tests::goto_def_for_ufcs_trait_methods_through_self ... ok
test goto_type_definition::tests::goto_type_definition_works_simple ... ok
test highlight_related::tests::test_hl_disabled_yield ... ok
test highlight_related::tests::test_hl_yield_nested_fn ... ok
test highlight_related::tests::test_hl_inner_tail_exit_points ... ok
test goto_type_definition::tests::goto_type_definition_works_simple_ref ... ok
test goto_definition::tests::goto_impl_of_trait_fn::path_call ... ok
test highlight_related::tests::test_hl_yield_points ... ok
test goto_type_definition::tests::goto_def_for_self_param ... ok
test goto_definition::tests::goto_impl_of_trait_fn::method_call_on_generic ... ok
test goto_definition::tests::unknown_assoc_ty ... ok
test goto_definition::tests::goto_through_included_file ... ok
test goto_type_definition::tests::goto_def_considers_generics ... ok
test goto_definition::tests::goto_def_in_macro_multi ... ok
test highlight_related::tests::test_hl_self_in_module ... ok
test highlight_related::tests::test_hl_module ... ok
test highlight_related::tests::test_hl_yield_points2 ... ok
test goto_definition::tests::goto_bin_op ... ok
test highlight_related::tests::test_hl_yield_nested_async_blocks ... ok
test goto_type_definition::tests::goto_type_definition_for_tuple_field ... ok
test highlight_related::tests::test_hl_disabled_exit ... ok
test expand_macro::tests::macro_expand_derive2 ... ok
test goto_definition::tests::goto_def_for_assoc_ty_in_path_multiple ... ok
test hover::tests::const_generic_order ... ok
test highlight_related::tests::test_hl_self_in_crate_root ... ok
test goto_definition::tests::goto_impl_of_trait_fn::method_call ... ok
test hover::tests::hover_clippy_lint ... ok
test goto_type_definition::tests::goto_type_definition_works_through_macro ... ok
test highlight_related::tests::test_hl_local ... ok
test goto_definition::tests::goto_impl_of_trait_fn::method_call_defaulted ... ok
test hover::tests::hover_comments_dont_highlight_parent ... ok
test goto_type_definition::tests::goto_type_definition_record_pat_field ... ok
test hover::tests::hover_const_generic_type_alias ... ok
test hover::tests::hover_doc_outer_inner_attribue ... ok
test hover::tests::function_doesnt_shadow_crate_in_use_tree ... ok
test hover::tests::hover_doc_outer_inner ... ok
test highlight_related::tests::test_hl_field_shorthand ... ok
test hover::tests::hover_attr_path_qualifier ... ok
test highlight_related::tests::test_hl_prefer_ref_over_tail_exit ... ok
test goto_definition::tests::goto_def_when_used_on_definition_name_itself ... ok
test hover::tests::hover_builtin ... ok
test hover::tests::hover_feature ... ok
test goto_type_definition::tests::goto_type_definition_record_expr_field ... ok
test hover::tests::hover_const_param ... ok
test goto_definition::tests::goto_definition_on_self ... ok
test hover::tests::hover_doc_block_style_indentend ... ok
test hover::tests::hover_field_offset ... ok
test highlight_related::tests::test_hl_tuple_fields ... ok
test hover::tests::hover_keyword_as_primitive ... ok
test hover::tests::const_generic_negative_i8_literal ... ok
test hover::tests::array_repeat_exp ... ok
test hover::tests::const_generic_zero_i8_literal ... ok
test goto_definition::tests::goto_within_macro ... ok
test hover::tests::const_generic_positive_i8_literal ... ok
test hover::tests::hover_lint ... ok
test hover::tests::const_generic_char_literal ... ok
test hover::tests::hover_keyword ... ok
test hover::tests::const_generic_bool_literal ... ok
test highlight_related::tests::test_hl_local_in_attr ... ok
test hover::tests::hover_for_local_variable ... ok
test hover::tests::hover_label ... ok
test hover::tests::hover_lifetime ... ok
test hover::tests::hover_for_local_variable_pat ... ok
test hover::tests::hover_inert_attr ... ok
test hover::tests::hover_intra_doc_links ... ok
test hover::tests::hover_mod_def ... ok
test hover::tests::hover_for_param_edge ... ok
test hover::tests::hover_dollar_crate ... ok
test highlight_related::tests::test_hl_never_call_is_exit_point ... ok
test hover::tests::hover_intra_in_macro ... ok
test hover::tests::hover_intra_in_attr ... ok
test hover::tests::hover_range_shows_nothing_when_invalid ... ok
test hover::tests::hover_local_var_edge ... ok
test hover::tests::hover_record_variant ... ok
test highlight_related::tests::test_hl_multi_local ... ok
test hover::tests::hover_self_in_use ... ok
test hover::tests::hover_field_pat_shorthand_ref_match_ergonomics ... ok
test hover::tests::hover_enum_variant ... ok
test hover::tests::hover_default_generic_types ... ok
test goto_definition::tests::goto_impl_of_trait_fn::wc_case_is_ok ... ok
test hover::tests::hover_descend_macros_avoids_duplicates ... ok
test hover::tests::hover_displays_normalized_crate_names ... ok
test hover::tests::hover_record_variant_field ... ok
test hover::tests::hover_keyword_doc ... ok
test hover::tests::hover_shows_fn_signature_on_fn_name ... ok
test hover::tests::hover_shows_fn_doc_attr_raw_string ... ok
test goto_definition::tests::goto_through_format ... ok
test hover::tests::hover_const_pat ... ok
test hover::tests::hover_shows_fn_doc ... ok
test hover::tests::hover_const_static ... ok
test goto_implementation::tests::goto_implementation_to_builtin_derive ... ok
test hover::tests::hover_self_param_shows_type ... ok
test hover::tests::hover_remove_markdown_if_configured ... ok
test hover::tests::hover_range_for_pat ... ok
test hover::tests::test_hover_function_pointer_no_identifier ... ok
test goto_definition::tests::goto_index_op ... ok
test hover::tests::hover_self_param_shows_type_for_arbitrary_self_type ... ok
test hover::tests::hover_attribute_in_macro ... ok
test hover::tests::hover_shows_type_of_an_expression ... ok
test hover::tests::test_hover_enum_has_impl_action ... ok
test hover::tests::test_hover_function_pointer_show_identifiers ... ok
test hover::tests::test_hover_const_param_has_goto_type_action ... ok
test hover::tests::test_hover_external_url ... ok
test hover::tests::hover_shows_all_macro_descends ... ok
test hover::tests::hover_range_shows_type_actions ... ok
test hover::tests::hover_trait_impl_assoc_item_def_doc_forwarding ... ok
test hover::tests::hover_shows_fn_signature_with_type_params ... ok
test hover::tests::hover_const_eval_in_generic_trait ... ok
test hover::tests::hover_ranged_macro_call ... ok
test hover::tests::test_hover_function_show_types ... ok
test hover::tests::hover_rename ... ok
test hover::tests::hover_range_shows_coercions_if_applicable_expr ... ok
test hover::tests::test_hover_extern_crate ... ok
test hover::tests::test_hover_dyn_arg_has_goto_type_action ... ok
test hover::tests::string_shadowed_with_inner_items ... ok
test goto_definition::tests::path_call_multiple_trait_impl ... ok
test hover::tests::hover_range_functions ... ok
test hover::tests::hover_omits_unnamed_where_preds ... ok
test hover::tests::hover_range_shows_unit_for_statements ... ok
test hover::tests::hover_const_eval_variant ... ok
test goto_definition::tests::goto_impl_of_trait_fn::where_clause_can_work ... ok
test hover::tests::hover_range_math ... ok
test hover::tests::hover_shows_struct_field_info ... ok
test hover::tests::test_hover_arg_impl_trait_has_goto_type_action ... ok
test hover::tests::hover_rest_pat ... ok
test hover::tests::hover_some ... ok
test goto_definition::tests::goto_def_derive_input ... ok
test hover::tests::hover_macro_expanded_function ... ok
test hover::tests::test_hover_arg_generic_impl_trait_has_goto_type_action ... ok
test hover::tests::hover_range_arrays ... ok
test expand_macro::tests::macro_expand_derive_multi ... ok
test hover::tests::test_hover_arg_impl_traits_has_goto_type_action ... ok
test goto_definition::tests::goto_prefix_op ... ok
test hover::tests::test_hover_mod_with_same_name_as_function ... ok
test hover::tests::hover_for_param_with_multiple_traits ... ok
test goto_definition::tests::goto_try_op ... ok
test hover::tests::test_hover_async_block_impl_trait_has_goto_type_action ... ok
test hover::tests::test_hover_no_links ... ok
test hover::tests::test_hover_self_has_impl_action ... ok
test hover::tests::test_hover_generic_dyn_arg_has_goto_type_action ... ok
test hover::tests::test_hover_trait_has_impl_action ... ok
test hover::tests::test_hover_dyn_return_has_goto_type_action ... ok
test hover::tests::test_hover_tuple_field ... ok
test hover::tests::test_hover_shadowing_pat ... ok
test hover::tests::test_hover_trait_show_qualifiers ... ok
test hover::tests::test_hover_struct_has_impl_action ... ok
test hover::tests::hover_derive_input ... ok
test hover::tests::test_hover_union_has_impl_action ... ok
test hover::tests::test_hover_test_mod_has_action ... ok
test hover::tests::test_hover_through_literal_string_in_builtin_macro ... ok
test hover::tests::test_hover_function_show_qualifiers ... ok
test goto_definition::tests::goto_await_into_future_poll ... ok
test hover::tests::test_hover_macro2_invocation ... ok
test hover::tests::test_hover_test_has_action ... ok
test hover::tests::test_hover_unknown_target ... ok
test hover::tests::test_hover_trait_assoc_typealias ... ok
test highlight_related::tests::test_multi_macro_usage ... ok
test hover::tests::test_hover_macro_invocation ... ok
test hover::tests::test_hover_struct_doc_attr_multiple_and_mixed ... ok
test hover::tests::test_hover_struct_doc_attr ... ok
test hover::tests::static_const_macro_expanded_body ... ok
test hover::tests::test_hover_struct_has_goto_type_action ... ok
test hover::tests::test_hover_struct_doc_comment ... ok
test hover::tests::test_hover_non_ascii_space_doc ... ok
test hover::tests::test_hover_self_has_go_to_type ... ok
test hover::tests::test_hover_generic_return_impl_trait_has_goto_type_action ... ok
test hover::tests::test_hover_through_literal_string_in_macro ... ok
test hover::tests::test_hover_return_impl_trait_has_goto_type_action ... ok
test hover::tests::test_hover_through_attr ... ok
test hover::tests::test_hover_generic_struct_has_goto_type_actions ... ok
test hover::tests::test_hover_through_expr_in_macro ... ok
test hover::tests::test_hover_type_param_has_goto_type_action ... ok
test hover::tests::test_hover_multiple_actions ... ok
test hover::tests::test_hover_infer_associated_const_in_pattern ... ok
test hover::tests::test_hover_through_expr_in_macro_recursive ... ok
test goto_definition::tests::goto_bin_op_multiple_impl ... ok
test hover::tests::test_hover_return_impl_traits_has_goto_type_action ... ok
test hover::tests::test_hover_generic_struct_has_flattened_goto_type_actions ... ok
test hover::tests::test_hover_goto_type_action_links_order ... ok
test hover::tests::hover_generic_assoc ... ok
test hover::tests::test_hover_infer_associated_method_result ... ok
test hover::tests::test_hover_through_macro ... ok
test hover::tests::test_hover_infer_associated_method_exact ... ok
test hover::tests::test_hover_generic_return_impl_traits_has_goto_type_action ... ok
test hover::tests::test_hover_through_func_in_macro_recursive ... ok
test inlay_hints::bind_pat::tests::return_type_hints_for_closure_without_block ... ok
test hover::tests::hover_shows_long_type_of_an_expression ... ok
test hover::tests::test_hover_variadic_function ... ok
test hover::tests::test_hover_macro_generated_struct_fn_doc_comment ... ok
test hover::tests::test_hover_through_assert_macro ... ok
test inlay_hints::adjustment::tests::never_to_never_is_never_shown ... ok
test goto_definition::tests::goto_await_poll ... ok
test hover::tests::test_hover_macro_generated_struct_fn_doc_attr ... ok
test hover::tests::test_hover_tuple_has_goto_type_actions ... ok
test hover::tests::type_param_sized_bounds::single_implicit ... ok
test hover::tests::hover_try_expr ... ok
test hover::tests::type_param_sized_bounds::single_explicit ... ok
test join_lines::tests::join_last_line_empty ... ok
test join_lines::tests::join_lines_adds_comma_for_block_in_match_arm ... ok
test join_lines::tests::join_assignments ... ok
test hover::tests::type_param_sized_bounds::multiple_implicit ... ok
test hover::tests::type_param_sized_bounds::multiple_relaxed ... ok
test hover::tests::hover_deref ... ok
test inlay_hints::bind_pat::tests::default_generic_types_should_not_be_displayed ... ok
test join_lines::tests::join_lines_keeps_comma_with_single_arg_tuple ... ok
test join_lines::tests::join_lines_mandatory_blocks_block ... ok
test join_lines::tests::join_two_ifs_with_existing_else ... ok
test join_lines::tests::join_string_literal ... ok
test join_lines::tests::join_lines_multiline_in_block ... ok
test join_lines::tests::join_two_ifs ... ok
test hover::tests::test_hover_associated_type_has_goto_type_action ... ok
test join_lines::tests::test_join_lines_block ... ok
test join_lines::tests::test_join_lines_commented_block ... ok
test hover::tests::type_param_sized_bounds::single_relaxed ... ok
test join_lines::tests::join_lines_keeps_comma_for_block_in_match_arm ... ok
test join_lines::tests::test_join_lines_doc_comments ... ok
test join_lines::tests::test_join_lines_mod_comments ... ok
test hover::tests::type_param_sized_bounds::multiple_explicit ... ok
test join_lines::tests::test_join_lines_multiline_comments_2 ... ok
test join_lines::tests::test_join_lines_diverging_block ... ok
test join_lines::tests::test_join_lines_normal_comments ... ok
test join_lines::tests::test_join_lines_comma ... ok
test join_lines::tests::test_join_lines_selection_dot_chain ... ok
test join_lines::tests::test_join_lines_multiline_comments_1 ... ok
test inlay_hints::tests::hints_disabled ... ok
test hover::tests::hover_type_param_sized_bounds ... ok
test join_lines::tests::test_join_lines_selection_fn_args ... ok
test join_lines::tests::test_join_lines_use_items_left ... ok
test join_lines::tests::test_join_lines_lambda_block ... ok
test inlay_hints::implicit_static::tests::hints_lifetimes_static ... ok
test join_lines::tests::test_join_lines_use_items_right_comma ... ok
test join_lines::tests::test_join_lines_selection_struct ... ok
test join_lines::tests::test_join_lines_use_tree ... ok
test join_lines::tests::test_join_lines_selection_lambda_block_body ... ok
test inlay_hints::fn_lifetime_fn::tests::hints_lifetimes_named ... ok
test inlay_hints::bind_pat::tests::type_hints_only ... ok
test join_lines::tests::test_join_lines_use_items_right ... ok
test hover::tests::hover_shows_fn_signature ... ok
test move_item::tests::handles_empty_file ... ok
test inlay_hints::chaining::tests::chaining_hints_without_newlines ... ok
test matching_brace::tests::test_matching_brace ... ok
test move_item::tests::test_move_item ... ok
test inlay_hints::param_name::tests::param_name_same_as_fn_name ... ok
test hover::tests::hover_deref_expr ... ok
test move_item::tests::test_moves_arg_down ... ok
test move_item::tests::test_move_use_up ... ok
test move_item::tests::test_move_impl_up ... ok
test move_item::tests::test_moves_let_stmt_up ... ok
test move_item::tests::test_moves_arg_up ... ok
test inlay_hints::closing_brace::tests::hints_closing_brace ... ok
test inlay_hints::param_name::tests::param_hints_on_closure ... ok
test inlay_hints::param_name::tests::never_hide_param_when_multiple_params ... ok
test move_item::tests::test_cursor_at_item_end ... ok
test inlay_hints::param_name::tests::param_hints_only ... ok
test inlay_hints::bind_pat::tests::hint_truncation ... ok
test inlay_hints::param_name::tests::param_name_hints_show_for_literals ... ok
test move_item::tests::test_moves_generic_arg_up ... ok
test move_item::tests::test_moves_match_arm_up ... ok
test move_item::tests::test_moves_generic_param_up ... ok
test move_item::tests::test_moves_match_expr_up ... ok
test move_item::tests::test_moves_match_arm_down ... ok
test moniker::tests::moniker_for_trait ... ok
test move_item::tests::test_cursor_at_item_start ... ok
test move_item::tests::test_moves_variant_up ... ok
test moniker::tests::moniker_for_trait_type ... ok
test move_item::tests::test_nowhere_to_move ... ok
test inlay_hints::bind_pat::tests::let_statement ... ok
test moniker::tests::moniker_for_trait_constant ... ok
test move_item::tests::test_moves_type_bound_up ... ok
test move_item::tests::test_nowhere_to_move_stmt ... ok
test move_item::tests::test_moves_param ... ok
test move_item::tests::test_nowhere_to_move_arg ... ok
test move_item::tests::test_weird_nesting ... ok
test inlay_hints::param_name::tests::param_name_similar_to_fn_name_still_hints ... ok
test inlay_hints::bind_pat::tests::closures ... ok
test move_item::tests::test_prioritizes_trait_items ... ok
test hover::tests::test_hover_self ... ok
test hover::tests::hover_type_param ... ok
test parent_module::tests::test_resolve_multi_parent_crate ... ok
test parent_module::tests::test_resolve_crate_root ... ok
test move_item::tests::test_moves_expr_up ... ok
test parent_module::tests::test_resolve_parent_module ... ok
test parent_module::tests::test_resolve_parent_module_for_inline ... ok
test moniker::tests::moniker_for_trait_impl_function ... ok
test moniker::tests::no_moniker_for_local ... ok
test parent_module::tests::test_resolve_parent_module_on_module_decl ... ok
test inlay_hints::param_name::tests::param_hints_look_through_as_ref_and_clone ... ok
test moniker::tests::moniker_for_field ... ok
test parent_module::tests::test_resolve_multi_parent_module ... ok
test hover::tests::type_param_sized_bounds::mixed ... ok
test inlay_hints::bind_pat::tests::unit_structs_have_no_type_hints ... ok
test hover::tests::hover_deref_expr_with_coercion ... ok
test references::tests::macro_doesnt_reference_attribute_on_call ... ok
test inlay_hints::param_name::tests::param_name_similar_to_fn_name ... ok
test inlay_hints::binding_mode::tests::hints_binding_modes ... ok
test inlay_hints::bind_pat::tests::infer_call_method_return_associated_types_with_generic ... ok
test references::tests::test_find_all_refs_decl_module_on_self ... ok
test references::tests::test_find_all_refs_decl_module_on_self_crate_root ... ok
test references::tests::test_find_all_refs_decl_module ... ok
test highlight_related::tests::test_hl_trait_impl_methods ... ok
test references::tests::test_find_all_refs_enum_var_name ... ok
test references::tests::test_basic_highlight_decl_no_write ... ok
test inlay_hints::param_name::tests::self_param_hints ... ok
test references::tests::proc_macro ... ok
test references::tests::test_basic_highlight_read_write ... ok
test inlay_hints::bind_pat::tests::multi_dyn_trait_bounds ... ok
test references::tests::search_filters_by_range ... ok
test hover::tests::hover_try_expr_res ... ok
test references::tests::test_attr_differs_from_fn_with_same_name ... ok
test moniker::tests::basic ... ok
test references::tests::test_find_all_refs_enum_var_field ... ok
test references::tests::test_find_all_refs_impl_item_name ... ok
test references::tests::test_decl_macro_references ... ok
test inlay_hints::chaining::tests::chaining_hints_ignore_comments ... ok
test inlay_hints::bind_pat::tests::type_hints_bindings_after_at ... ok
test inlay_hints::chaining::tests::struct_access_chaining_hints ... ok
test references::tests::test_basic_highlight_field_read_write ... ok
test inlay_hints::bind_pat::tests::while_expr ... ok
test references::tests::test_find_all_refs_for_fn_param ... ok
test inlay_hints::bind_pat::tests::match_arm_list ... ok
test references::tests::test_find_all_refs_for_param_inside ... ok
test references::tests::test_find_lifetimes_type_alias ... ok
test references::tests::attr ... ok
test references::tests::test_enum_before_space ... ok
test references::tests::test_find_all_refs_macro_def ... ok
test references::tests::test_enum_with_generic_type ... ok
test hover::tests::hover_try_expr_option ... ok
test references::tests::test_find_all_refs_field_name ... ok
test references::tests::attr_expanded ... ok
test references::tests::test_find_labels ... ok
test references::tests::test_find_all_refs_nested_module ... ok
test references::tests::test_find_all_refs_for_local ... ok
test references::tests::test_find_all_refs_enum_var_privacy ... ok
test references::tests::test_const_in_pattern ... ok
test references::tests::multi_def ... ok
test references::tests::test_trait ... ok
test references::tests::test_find_const_param ... ok
test references::tests::test_enum_after_space ... ok
test references::tests::test_find_all_refs_enum_var_pat ... ok
test inlay_hints::chaining::tests::generic_chaining_hints ... ok
test references::tests::test_find_lifetimes_trait_impl ... ok
test references::tests::test_find_all_refs_struct_pat ... ok
test references::tests::test_enum_for_tuple ... ok
test inlay_hints::chaining::tests::hints_in_attr_call ... ok
test references::tests::test_find_self_refs_decl ... ok
test references::tests::test_primitives ... ok
test references::tests::test_find_all_refs_super_mod_vis ... ok
test references::tests::test_self_variant_with_payload ... ok
test references::tests::test_find_lifetimes_function ... ok
test rename::tests::regression_13498 ... ok
test references::tests::test_map_range_to_original ... ok
test references::tests::test_transitive ... ok
test rename::tests::test_prepare_rename_keyword ... ok
test references::tests::test_struct_literal_before_space ... ok
test references::tests::attr_assoc_item ... ok
test references::tests::test_struct_literal_with_generic_type ... ok
test references::tests::test_map_range_to_original_ref ... ok
test references::tests::test_find_all_refs_two_modules ... ok
test references::tests::test_struct_literal_for_union ... ok
test references::tests::test_trait_self ... ok
test rename::tests::test_owned_self_to_parameter ... ok
test inlay_hints::fn_lifetime_fn::tests::hints_lifetimes_trivial_skip ... ok
test references::tests::test_find_struct_function_refs_outside_module ... ok
test references::tests::test_struct_literal_for_tuple ... ok
test references::tests::derive ... ok
test rename::tests::test_enum_variant_from_module_1 ... ok
test rename::tests::test_rename_fails_on_aliases ... ok
test references::tests::test_variant_record_after_space ... ok
test rename::tests::test_enum_variant_from_module_2 ... ok
test rename::tests::test_prepare_rename_builtin ... ok
test rename::tests::test_prepare_rename_in_macro ... ok
test rename::tests::test_prepare_rename_self ... ok
test rename::tests::test_rename_lifetimes ... ok
test rename::tests::defs_from_macros_arent_renamed ... ok
test references::tests::test_self_ty ... ok
test rename::tests::attributed_item ... ok
test rename::tests::test_parameter_to_self_impl_ref ... ok
test references::tests::test_find_all_refs_with_scope ... ok
test rename::tests::test_parameter_to_self_error_not_first ... ok
test inlay_hints::fn_lifetime_fn::tests::hints_lifetimes ... ok
test rename::tests::test_rename_label ... ok
test rename::tests::test_rename_for_param_inside ... ok
test rename::tests::test_rename_mod_invalid ... ok
test references::tests::test_find_self_refs ... ok
test rename::tests::test_rename_mod_in_dir ... ok
test rename::tests::test_rename_mod_for_crate_root ... ok
test rename::tests::test_parameter_to_self_error_no_impl ... ok
test rename::tests::test_field_shorthand_correct_struct ... ok
test rename::tests::rename_multi_local ... ok
test inlay_hints::bind_pat::tests::if_expr ... ok
test rename::tests::test_rename_mod ... ok
test rename::tests::test_rename_for_mut_param ... ok
test rename::tests::test_rename_mod_in_macro ... ok
test rename::tests::test_rename_mod_ref_by_super ... ok
test rename::tests::test_rename_builtin ... ok
test rename::tests::test_parameter_to_self ... ok
test rename::tests::test_rename_local_in_field_shorthand ... ok
test rename::tests::test_rename_ignores_self_ty ... ok
test rename::tests::test_prepare_rename_namelikes ... ok
test rename::tests::test_module_rename_in_path ... ok
test rename::tests::test_rename_for_macro_args ... ok
test rename::tests::test_rename_to_invalid_identifier_lifetime2 ... ok
test rename::tests::test_rename_binding_in_destructure_param_pat ... ok
test references::tests::test_variant_tuple_before_paren ... ok
test inlay_hints::bind_pat::tests::check_hint_range_limit ... ok
test rename::tests::test_rename_refs_for_fn_param ... ok
test references::tests::test_struct_literal_after_space ... ok
test rename::tests::test_rename_for_macro_define_fn ... ok
test rename::tests::test_rename_mod_filename_and_path ... ok
test rename::tests::test_rename_to_invalid_identifier2 ... ok
test rename::tests::test_rename_to_invalid_identifier1 ... ok
test rename::tests::test_rename_to_invalid_identifier3 ... ok
test rename::tests::test_rename_trait_method_prefix_of_second ... ok
test rename::tests::test_rename_local_put_init_shorthand ... ok
test rename::tests::in_macro_multi_mapping ... ok
test rename::tests::test_rename_bind_pat ... ok
test rename::tests::test_rename_for_local ... ok
test rename::tests::test_rename_field_put_init_shorthand ... ok
test rename::tests::test_rename_field_in_pat_in_macro_doesnt_shorthand ... ok
test rename::tests::test_prepare_rename_tuple_field ... ok
test rename::tests::test_rename_to_underscore_invalid ... ok
test rename::tests::test_rename_to_invalid_identifier_lifetime ... ok
test rename::tests::test_rename_field_in_field_shorthand ... ok
test rename::tests::test_rename_self ... ok
test rename::tests::test_rename_for_macro_define_fn_rev ... ok
test rename::tests::test_rename_to_underscore ... ok
test rename::tests::test_self_to_self ... ok
test rename::tests::test_rename_unresolved_reference ... ok
test rename::tests::test_rename_to_raw_identifier ... ok
test inlay_hints::param_name::tests::parameter_hint_heuristics ... ok
test rename::tests::test_rename_macro_multiple_occurrences ... ok
test rename::tests::test_rename_mod_in_use_tree ... ok
test rename::tests::test_rename_struct_field ... ok
test runnables::tests::outline_submodule2 ... ok
test rename::tests::test_rename_for_macro_args_rev ... ok
test runnables::tests::outline_submodule1 ... ok
test rename::tests::test_rename_unusually_nested_mod ... ok
test runnables::tests::dont_recurse_in_outline_submodules ... ok
test inlay_hints::param_name::tests::function_call_parameter_hint ... ok
test runnables::tests::find_no_tests ... ok
test runnables::tests::doc_test_macro_export_mbe ... ok
test rename::tests::test_rename_mod_recursive ... ok
test rename::tests::test_rename_binding_in_destructure_pat ... ok
test runnables::tests::test_runnables_module ... ok
test runnables::tests::test_runnables_no_test_function_in_module ... ok
test runnables::tests::test_runnables_with_feature ... ok
test runnables::tests::attributed_module ... ok
test runnables::tests::test_runnables_with_features ... ok
test rename::tests::test_struct_field_complex_ident_pat ... ok
test rename::tests::test_shadow_local_for_struct_shorthand ... ok
test rename::tests::test_rename_tuple_field ... ok
test rename::tests::test_self_in_path_to_parameter ... ok
test rename::tests::test_self_to_parameter ... ok
test runnables::tests::find_direct_fn_test ... ok
test runnables::tests::test_runnables ... ok
test runnables::tests::test_runnables_doc_test_in_impl ... ok
test runnables::tests::test_doc_runnables_impl_mod ... ok
test runnables::tests::doc_test_type_params ... ok
test rename::tests::test_struct_field_pat_into_shorthand ... ok
test ssr::tests::not_applicable_comment_not_ssr ... ok
test runnables::tests::big_mac ... ok
test rename::tests::test_struct_local_pat_into_shorthand ... ok
test syntax_highlighting::tests::benchmark_syntax_highlighting_long_struct ... ok
test runnables::tests::find_direct_struct_test ... ok
test runnables::tests::only_modules_with_test_functions_or_more_than_one_test_submodule_have_runners ... ok
test syntax_highlighting::tests::benchmark_syntax_highlighting_parser ... ok
test runnables::tests::test_runnables_in_macro ... ok
test syntax_highlighting::tests::syntax_highlighting_not_quadratic ... ok
test hover::tests::hover_const_eval ... ok
test inlay_hints::bind_pat::tests::shows_constructor_type_hints_when_enabled ... ok
test runnables::tests::test_paths_with_raw_ident ... ok
test ssr::tests::resolve_edits_false ... ok
test syntax_highlighting::tests::ranges_sorted ... ok
test inlay_hints::bind_pat::tests::complete_for_hint ... ok
test signature_help::tests::call_info_bad_offset ... ok
test runnables::tests::test_runnables_doc_test ... ok
test inlay_hints::bind_pat::tests::fn_hints ... ok
test signature_help::tests::no_assoc_types_outside_type_bounds ... ok
test runnables::tests::find_indirect_fn_test ... ok
test runnables::tests::tests_are_unique ... ok
test ssr::tests::resolve_edits_true ... ok
test signature_help::tests::test_generics_simple ... ok
test signature_help::tests::test_generics_on_variant ... ok
test static_index::tests::multi_crate ... ok
test inlay_hints::bind_pat::tests::fn_hints_ptr_rpit_fn_parentheses ... ok
test syntax_highlighting::tests::test_extern_crate ... ok
test static_index::tests::struct_and_enum ... ok
test typing::on_enter::tests::continues_another_doc_comment ... ok
test signature_help::tests::test_generics_in_trait_ufcs ... ok
test signature_help::tests::test_supertrait_assoc ... ok
test rename::tests::test_rename_trait_const ... ok
test typing::on_enter::tests::continues_end_of_line_comment_with_space ... ok
test signature_help::tests::call_info_for_fn_ptr ... ok
test signature_help::tests::cant_call_struct_record ... ok
test typing::on_enter::tests::continues_code_comment_in_the_middle_of_line ... ok
test syntax_highlighting::tests::test_ranges ... ok
test syntax_tree::tests::test_syntax_tree_with_range ... ok
test typing::on_enter::tests::does_not_continue_before_doc_comment ... ok
test syntax_tree::tests::test_syntax_tree_without_range ... ok
test signature_help::tests::test_fn_signature_with_docs ... ok
test signature_help::tests::test_fn_signature_with_docs_impl ... ok
test signature_help::tests::test_fn_signature_for_method_with_arg ... ok
test typing::on_enter::tests::continues_code_comment_in_the_middle_several_lines ... ok
test signature_help::tests::test_fn_signature_for_impl ... ok
test signature_help::tests::call_info_for_lambdas ... ok
test typing::on_enter::tests::does_not_indent_use_tree_list_when_not_at_curly_brace ... ok
test typing::on_enter::tests::does_not_indent_multiline_use_tree_list ... ok
test signature_help::tests::fully_qualified_syntax ... ok
test typing::on_enter::tests::indents_nested_blocks ... ok
test signature_help::tests::generic_struct ... ok
test typing::on_enter::tests::does_not_indent_empty_block ... ok
test signature_help::tests::test_fn_signature_for_method_with_arg_as_assoc_fn ... ok
test typing::on_enter::tests::continues_doc_comment ... ok
test typing::on_enter::tests::does_not_indent_multiline_block ... ok
test typing::on_enter::tests::does_not_continue_end_of_line_comment ... ok
test typing::on_enter::tests::indents_block_expr ... ok
test signature_help::tests::works_for_enum_variants ... ok
test typing::tests::adds_space_after_return_type ... ok
test typing::tests::adds_closing_angle_bracket_for_generic_args ... ok
test signature_help::tests::test_fn_signature_two_args_empty ... ok
test typing::on_enter::tests::indents_fn_body_block ... ok
test signature_help::tests::cant_call_enum_record ... ok
test typing::on_enter::tests::indents_match_arm ... ok
test typing::tests::adds_closing_angle_bracket_for_generic_params ... ok
test typing::tests::dont_indent_freestanding_dot ... ok
test typing::tests::indents_continued_chain_call ... ok
test typing::tests::indents_middle_of_chain_call ... ok
test typing::tests::dont_add_closing_angle_bracket_for_comparison ... ok
test typing::on_enter::tests::indents_block_with_statement ... ok
test typing::tests::test_semi_after_let ... ok
test typing::tests::indents_new_chain_call_with_semi ... ok
test syntax_tree::tests::test_syntax_tree_inside_string ... ok
test typing::tests::indents_new_chain_call ... ok
test typing::on_enter::tests::trims_all_trailing_whitespace ... ok
test typing::tests::assign_to_eq ... ok
test signature_help::tests::test_fn_signature_for_method_self ... ok
test typing::tests::indents_new_chain_call_with_let ... ok
test typing::tests::noop_in_string_literal ... ok
test typing::tests::noop_in_item_position_with_macro ... ok
test signature_help::tests::test_generics_in_method_call ... ok
test signature_help::tests::test_fn_signature_no_params ... ok
test typing::tests::dont_add_closing_angle_bracket_if_it_is_already_there ... ok
test signature_help::tests::test_fn_signature_with_docs_simple ... ok
test signature_help::tests::impl_trait ... ok
test signature_help::tests::test_generic_param_in_method_call ... ok
test typing::tests::regression_629 ... ok
test typing::on_enter::tests::does_not_indent_block_with_too_much_content ... ok
test signature_help::tests::test_lots_of_generics ... ok
test typing::on_enter::tests::does_not_indent_use_tree_list_without_curly_braces ... ok
test syntax_highlighting::tests::test_lifetime_highlighting ... ok
test typing::tests::adds_closing_brace_for_use_tree ... ok
test syntax_highlighting::tests::test_mod_hl_injection ... ok
test typing::on_enter::tests::indents_use_tree_list ... ok
test typing::tests::test_semi_after_assign ... ok
test signature_help::tests::test_fn_signature_two_args_first_generics ... ok
test signature_help::tests::fn_signature_for_call_in_macro ... ok
test typing::tests::adds_closing_brace_for_expr ... ok
test syntax_highlighting::tests::test_keyword_highlighting ... ok
test syntax_highlighting::tests::test_associated_function ... ok
test signature_help::tests::test_fn_signature_for_generic_method ... ok
test static_index::tests::derives ... ok
test signature_help::tests::works_for_tuple_structs ... ok
test syntax_highlighting::tests::test_rainbow_highlighting ... ok
test navigation_target::tests::test_world_symbols_are_case_sensitive ... ok
test syntax_highlighting::tests::test_operators ... ok
test navigation_target::tests::test_nav_for_symbol ... ok
test signature_help::tests::call_info_for_unclosed_call ... ok
test inlay_hints::bind_pat::tests::skip_constructor_and_enum_type_hints ... ok
test signature_help::tests::test_nested_method_in_lambda ... ok
test inlay_hints::bind_pat::tests::shorten_iterator_hints ... ok
test syntax_highlighting::tests::test_injection ... ok
test signature_help::tests::regression_13579 ... ok
test inlay_hints::bind_pat::tests::skip_closure_type_hints ... ok
test rename::tests::test_rename_trait_method ... ok
test signature_help::tests::test_generic_kinds ... ok
test syntax_highlighting::tests::macros ... ok
test signature_help::tests::test_multiline_argument ... ok
test signature_help::tests::outside_of_arg_list ... ok
test signature_help::tests::test_fn_signature_with_docs_from_actix ... ok
test syntax_highlighting::tests::test_default_library ... ok
test inlay_hints::bind_pat::tests::shorten_iterators_in_associated_params ... ok
test syntax_highlighting::tests::attributes ... ok
test syntax_highlighting::tests::test_crate_root ... ok
test signature_help::tests::test_fn_signature_two_args ... ok
test signature_help::tests::help_for_generic_call ... ok
test inlay_hints::chaining::tests::shorten_iterator_chaining_hints ... ok
test inlay_hints::adjustment::tests::adjustment_hints ... ok
test syntax_highlighting::tests::test_unsafe_highlighting ... ok
test syntax_highlighting::tests::test_highlight_doc_comment ... ok
test signature_help::tests::test_trait_assoc_types ... ok
test inlay_hints::bind_pat::tests::iterator_hint_regression_issue_12674 ... ok
test syntax_highlighting::tests::test_highlighting ... ok
test syntax_highlighting::tests::test_string_highlighting ... ok

test result: ok. 790 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.34s

     Running unittests src/main.rs (/home/y00577373/analysis/target/debug/deps/ide-1cf76afca9bc0c43)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests ide

running 11 tests
test src/doc_links.rs - doc_links::filename_and_frag_for_def (line 461) ... ignored
test src/doc_links.rs - doc_links::get_assoc_item_fragment (line 533) ... ignored
test src/doc_links.rs - doc_links::get_doc_base_url (line 414) ... ignored
test src/inlay_hints/bind_pat.rs - inlay_hints::bind_pat (line 2) - compile ... ok
test src/inlay_hints/param_name.rs - inlay_hints::param_name (line 2) - compile ... ok
test src/inlay_hints/implicit_static.rs - inlay_hints::implicit_static (line 2) - compile ... ok
test src/inlay_hints/closing_brace.rs - inlay_hints::closing_brace (line 2) - compile ... ok
test src/inlay_hints/binding_mode.rs - inlay_hints::binding_mode (line 2) - compile ... ok
test src/inlay_hints/adjustment.rs - inlay_hints::adjustment (line 2) - compile ... ok
test src/inlay_hints/fn_lifetime_fn.rs - inlay_hints::fn_lifetime_fn (line 2) - compile ... ok
test src/goto_definition.rs - goto_definition::try_filter_trait_item_definition (line 125) ... ok

test result: ok. 8 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out; finished in 0.17s

